config/routes.rb
Rails.application.routes.draw do

  # Admins
  devise_for :admins, :controllers => {sessions: 'admins/sessions'}
  namespace :admin do
    resources :users, only: [:index, :show, :update]
    resources :sessions, except: [:show]
    get 'overview', to: 'overview#index'
    get 'registration', to: 'registration#index'
    post 'registration', to: 'registration#checkin'
    root to: 'overview#index'
  end

  # Users
  devise_for :users, :controllers => {sessions: 'users/sessions', registrations: 'users/registrations'}

  root to: 'home#index'

  get 'participants', to: 'home#participants'
  # get 'registration', to: 'home#registration'
  # get 'resend', to: 'home#resend'
  # post 'resend', to: 'home#resend'
  get 'dev', to: 'dev#index'

  get 'sessions', to: 'home#sessions'

  get 'welcome/:id', to: 'home#welcome', as: 'welcome'

  match ":url" => 'home#comingsoon', :via => [:get], :constraints => { :url => /.*/ }, to: redirect('/comingsoon')

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Admin</title>
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag '/favicon.ico' %>
  </head>
  <body>
    <% if admin_signed_in? %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Admin", admin_root_path, class: "navbar-brand"%>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "Overview", admin_root_path %>
            </li>
            <li>
              <%= link_to "Users", admin_users_path %>
            </li>
            <li>
              <%= link_to "Sessions", admin_sessions_path %>
            </li>
            <li>
              <%= link_to "Registration", admin_registration_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text">Signed in as: <%= current_admin.email %></p>
            </li>
            <li>
              <%= link_to "Logout", destroy_admin_session_path, method: :delete %>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:image" content="<%= image_url('barcamp-fb-preview.png')%>" />
    <title>BarCamp Bangkhen 2016</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script type='text/javascript' src='http://maps.googleapis.com/maps/api/js?key=AIzaSyC1FcQP7QwH5W_mjVghIV7Lh06Ll9Ridqw'></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag '/favicon.ico' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>